content:
  - name: archive
    label: Архив (Статьи)
    type: collection
    path: src/content/archive
    extension: mdx
    format: frontmatter
    fields:
      - name: title
        label: Заголовок
        type: string
      - name: description
        label: Описание
        type: string
      - name: pubDate
        label: Дата
        type: date
      - name: body
        label: Текст статьи
        type: rich-text
media:
  input: src/assets
  output: /src/assets