name: Весёлый хомяк =]
collection_folder: content
publish_mode: editorial_workflow
backend:
  name: github
  repo: tarzzzan/astro-hamster
  branch: main
  site_domain: tarzzzan.ru

media_folder: static/img
public_folder: /img

collections:
  - name: posts
    label: Статьи
    folder: content/docs
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Описание, name: description, widget: string, required: false }
      - { label: Содержание, name: body, widget: markdown }
      - { label: Вес сортировки, name: weight, widget: number, required: false }

  - name: pages
    label: Страницы
    folder: content
    create: false
    files:
      - file: content/_index.md
        label: Главная
        name: index
        fields:
          - { label: Название, name: title, widget: string }
          - { label: Содержание, name: body, widget: markdown }
      
      - file: content/about.md
        label: О сайте
        name: about
        fields:
          - { label: Название, name: title, widget: string }
          - { label: Содержание, name: body, widget: markdown }