media:
  input: src/assets
  output: src/assets

content:
  - name: archive
    label: Статьи (Archive)
    type: collection
    path: src/content/archive
    format: frontmatter
    fields:
      - name: title
        label: Заголовок
        type: string
      - name: description
        label: Описание
        type: string
      - name: pubDate
        label: Дата (ГГГГ-ММ-ДД)
        type: date
      - name: draft
        label: Черновик
        type: boolean
      - name: body
        label: Текст
        type: rich-text

  - name: essay
    label: Эссе (Essay)
    type: collection
    path: src/content/essay
    format: frontmatter
    fields:
      - name: title
        label: Заголовок
        type: string
      - name: description
        label: Описание
        type: string
      - name: pubDate
        label: Дата (ГГГГ-ММ-ДД)
        type: date
      - name: body
        label: Текст
        type: rich-text

  - name: bits
    label: Короткие записи (Bits)
    type: collection
    path: src/content/bits
    format: frontmatter
    fields:
      - name: title
        label: Заголовок
        type: string
      - name: pubDate
        label: Дата (ГГГГ-ММ-ДД)
        type: date
      - name: body
        label: Текст
        type: rich-text

  - name: memo
    label: Заметки (Memo)
    type: collection
    path: src/content/memo
    format: frontmatter
    fields:
      - name: title
        label: Заголовок
        type: string
      - name: pubDate
        label: Дата (ГГГГ-ММ-ДД)
        type: date
      - name: body
        label: Текст
        type: rich-text