name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # или master, если у вас основная ветка так называется
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload with Astro
        uses: withastro/action@v3